bt_navigator:
  ros__parameters:
    use_sim_time: true
    global_frame: map
    robot_base_frame: base_link
    odom_topic: /rosbot_controller/odom
    transform_tolerance: 0.3
    default_server_timeout: 1000
    bt_loop_duration: 10
    wait_for_service_timeout: 1000
    default_nav_to_pose_bt_xml: /home/moose/rosbot_ws/src/rosbot_navigation/behavior_tree/navigation.xml
    default_nav_through_poses_bt_xml: /home/moose/rosbot_ws/src/rosbot_navigation/behavior_tree/navigation.xml