<?xml version="1.0"?>

<robot name="rosbot" xmlns:xacro="http://ros.org/wiki/xacro">

    <xacro:property name="wheel_radius" value="0.0425"/>
    <xacro:property name="wheel_thickness" value="0.0455"/>
    <xacro:property name="wheel_separation_x" value="0.106"/>
    <xacro:property name="wheel_separation_y" value="0.192"/>

    <link name="base_footprint"/>
    <link name="base_link">
        <visual>
            <geometry>
                <mesh filename="package://rosbot_description/meshes/rosbot/body.stl" scale="0.001 0.001 0.001"/>
            </geometry>
            <origin xyz="0 0 0" rpy="${pi/2} 0 ${pi/2}"/>
            <material name="orange">
                <color rgba="0.4 0.4 0.4 1"/>
            </material>
        </visual>
        <collision>
            <geometry>
                <box size="0.197 0.150 0.080"/>
            </geometry>
            <origin xyz=" 0 0 0.038" rpy="0 0 0"/>
        </collision>

        <inertial>
            <mass value="1.728" />
            <inertia ixx="0.004162" ixy="0.0"     ixz="0.0"
                                    iyy="0.00651" iyz="0.0"
                                                  izz="0.008828" />
            <origin xyz="0.0 0.0 0.038" rpy="0.0 0.0 0.0" />
          </inertial>

    </link>

    <joint name="base_joint" type="fixed">
        <parent link="base_footprint"/>
        <child link="base_link"/>
        <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0"/>
    </joint>

    <link name="cover_link">
        <visual>
            <geometry>
                <mesh filename="package://rosbot_description/meshes/rosbot/cover.stl" scale="0.001 0.001 0.001"/>
            </geometry>
            <origin xyz="0 0 0.015" rpy="${pi/2} 0 ${pi/2}"/>
            <material name="grey">
                <color rgba="1 0.27 0 1"/>
            </material>
        </visual>
    </link>
    
    <joint name="cover_joint" type="fixed">
        <parent link="base_link"/>
        <child link="cover_link"/>
        <origin xyz="0 0 0.0603" rpy="0 0 0"/>
    </joint>

    <link name="wheel_left_back_link">
        <visual>
            <geometry>
                <mesh filename="package://rosbot_description/meshes/rosbot/wheel_a.dae"/>
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </visual>

        <collision>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
            <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        </collision>
    </link>

    <joint name="wheel_left_back_joint" type="continuous">
        <parent link="base_link"/>
        <child link="wheel_left_back_link"/>
        <origin xyz="-${wheel_separation_x/2} ${wheel_separation_y/2} 0.015" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>
    </joint>

    <link name="wheel_left_forward_link">
        <visual>
            <geometry>
                <mesh filename="package://rosbot_description/meshes/rosbot/wheel_a.dae"/>
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </visual>

        <collision>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
            <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        </collision>
    </link>

    <joint name="wheel_left_forward_joint" type="continuous">
        <parent link="base_link"/>
        <child link="wheel_left_forward_link"/>
        <origin xyz="${wheel_separation_x/2} ${wheel_separation_y/2} 0.015" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>
    </joint>

    <link name="wheel_right_back_link">
        <visual>
            <geometry>
                <mesh filename="package://rosbot_description/meshes/rosbot/wheel_b.dae"/>
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </visual>

        <collision>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
            <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        </collision>
    </link>

    <joint name="wheel_right_back_joint" type="continuous">
        <parent link="base_link"/>
        <child link="wheel_right_back_link"/>
        <origin xyz="-${wheel_separation_x/2} -${wheel_separation_y/2} 0.015" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>
    </joint>

    <link name="wheel_right_forward_link">
        <visual>
            <geometry>
                <mesh filename="package://rosbot_description/meshes/rosbot/wheel_b.dae"/>
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </visual>

        <collision>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
            <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        </collision>
    </link>

    <joint name="wheel_right_forward_joint" type="continuous">
        <parent link="base_link"/>
        <child link="wheel_right_forward_link"/>
        <origin xyz="${wheel_separation_x/2} -${wheel_separation_y/2} 0.015" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>
    </joint>

    

</robot>
