<?xml version="1.0"?>

<robot name="rosbot" xmlns:xacro="http://ros.org/wiki/xacro">

    <xacro:property name="wheel_radius" value="0.0425"/>
    <xacro:property name="wheel_separation_x" value="0.106"/>
    <xacro:property name="wheel_separation_y" value="0.192"/>

    <link name="base_footprint"/>
    <link name="base_link">
        <visual>
            <geometry>
                <mesh filename="package://rosbot_description/meshes/rosbot/body.stl" scale="0.001 0.001 0.001"/>
            </geometry>
            <origin xyz="0 0 0" rpy="${pi/2} 0 ${pi/2}"/>
        </visual>

    </link>

    <joint name="base_joint" type="fixed">
        <parent link="base_footprint"/>
        <child link="base_link"/>
        <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0"/>
    </joint>

    <link name="cover_link">
        <visual>
            <geometry>
                <mesh filename="package://rosbot_description/meshes/rosbot/cover.stl" scale="0.001 0.001 0.001"/>
            </geometry>
            <origin xyz="0 0 0.015" rpy="${pi/2} 0 ${pi/2}"/>
        </visual>
    </link>
    
    <joint name="cover_joint" type="fixed">
        <parent link="base_link"/>
        <child link="cover_link"/>
        <origin xyz="0 0 0.0603" rpy="0 0 0"/>
    </joint>

    <link name="wheel_left_back_link">
        <visual>
            <geometry>
                <mesh filename="package://rosbot_description/meshes/rosbot/wheel_a.dae"/>
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </visual>
    </link>

    <joint name="wheel_left_back_joint" type="fixed">
        <parent link="base_link"/>
        <child link="wheel_left_back_link"/>
        <origin xyz="-${wheel_separation_x/2} ${wheel_separation_y/2} 0.015" rpy="0 0 0"/>
    </joint>

    <link name="wheel_left_forward_link">
        <visual>
            <geometry>
                <mesh filename="package://rosbot_description/meshes/rosbot/wheel_a.dae"/>
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </visual>
    </link>

    <joint name="wheel_left_forward_joint" type="fixed">
        <parent link="base_link"/>
        <child link="wheel_left_forward_link"/>
        <origin xyz="${wheel_separation_x/2} ${wheel_separation_y/2} 0.015" rpy="0 0 0"/>
    </joint>

    <link name="wheel_right_back_link">
        <visual>
            <geometry>
                <mesh filename="package://rosbot_description/meshes/rosbot/wheel_b.dae"/>
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </visual>
    </link>

    <joint name="wheel_right_back_joint" type="fixed">
        <parent link="base_link"/>
        <child link="wheel_right_back_link"/>
        <origin xyz="-${wheel_separation_x/2} -${wheel_separation_y/2} 0.015" rpy="0 0 0"/>
    </joint>

    <link name="wheel_right_forward_link">
        <visual>
            <geometry>
                <mesh filename="package://rosbot_description/meshes/rosbot/wheel_b.dae"/>
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </visual>
    </link>

    <joint name="wheel_right_forward_joint" type="fixed">
        <parent link="base_link"/>
        <child link="wheel_right_forward_link"/>
        <origin xyz="${wheel_separation_x/2} -${wheel_separation_y/2} 0.015" rpy="0 0 0"/>
    </joint>

    

</robot>
